variables:
  NIX_PATH: "nixpkgs=channel:nixos-unstable"

stages:
  - test
  - deploy

before_script:
  - echo "experimental-features = nix-command flakes" >> /etc/nix/nix.conf

build:
  script:
    - nix flake check
  tags:
    - nix

